// PS-RX - italiano e inglese nel pannello Decky.
//
// I testi italiani sono la chiave; con la lingua di Steam diversa dall'italiano si usa l'inglese.
// I testi che arrivano dal backend (impostazioni, errori, notifiche) li traduce main.py: il pannello gli
// passa la lingua con impostaLingua(). Una voce per riga: strumenti/chiavi_ts.py controlla che non manchi nulla.

const EN: Record<string, string> = {
  "WiFi \"{0}\" a posto": "WiFi \"{0}\" OK",
  "WiFi \"{0}\": problema": "WiFi \"{0}\": problem",
  "La prova del WiFi non ha dato risposta in tempo.": "The WiFi test did not answer in time.",
  "{0} (Ricollega l'USB del ricevitore.)": "{0} (Reconnect the receiver USB.)",
  "Nome (al massimo 15 caratteri)": "Name (up to 15 characters)",
  "Nome salvato.": "Name saved.",
  "Salva il nome": "Save the name",
  "Dimenticare il controller?": "Forget the controller?",
  "{0}: per riusarlo andrà abbinato di nuovo e le sue impostazioni si perdono.": "{0}: to use it again it must be paired again, and its settings are lost.",
  "Dimentica": "Forget",
  "Annulla": "Cancel",
  "Controller dimenticato.": "Controller forgotten.",
  "Dimentica questo controller": "Forget this controller",
  "Rete {0}": "Network {0}",
  "Salva": "Save",
  "Rete {0} salvata.": "Network {0} saved.",
  "Nome della rete (SSID)": "Network name (SSID)",
  "Password (vuota = mantieni quella salvata)": "Password (empty = keep the saved one)",
  "Password (vuota = rete aperta)": "Password (empty = open network)",
  "WPA3": "WPA3",
  "Solo se il router lo richiede: WPA2 va bene per quasi tutte le reti.": "Only if the router requires it: WPA2 works for almost every network.",
  "Solo reti a 2,4 GHz: il Pico 2 W non vede i 5 GHz. Se il router ha due nomi (per esempio Casa e Casa_5G) scegli quello a 2,4 GHz. Dopo il salvataggio usa Prova.": "2.4 GHz networks only: the Pico 2 W cannot see 5 GHz. If the router has two names (for example Home and Home_5G) choose the 2.4 GHz one. After saving, use Test.",
  "PC da svegliare": "PC to wake",
  "MAC della scheda di rete cablata del PC (formato AA:BB:CC:DD:EE:FF). Vuoto = nessuno.": "MAC of the PC's wired network adapter (format AA:BB:CC:DD:EE:FF). Empty = none.",
  "Destinazioni salvate.": "Targets saved.",
  "Gamepad · modalità {0}": "Gamepad · {0} mode",
  "Controller": "Controllers",
  "nessuno collegato": "none connected",
  "{0}. {1}: batteria {2}": "{0}. {1}: battery {2}",
  " (in carica)": " (charging)",
  "{0} · {1} report/s · {2} Hz · segnale {3}": "{0} · {1} reports/s · {2} Hz · signal {3}",
  "Posto {0} spento.": "Slot {0} turned off.",
  "Spegni": "Turn off",
  "Abbinamento in corso: tieni Create + PS (DualSense) o Share + PS (DualShock 4).": "Pairing in progress: hold Create + PS (DualSense) or Share + PS (DualShock 4).",
  "Finestra di 30 s: poi tieni Create + PS (DualSense) o Share + PS (DualShock 4) sul controller.": "30 s window: then hold Create + PS (DualSense) or Share + PS (DualShock 4) on the controller.",
  "Abbinamento aperto per 30 secondi.": "Pairing open for 30 seconds.",
  "Abbina un nuovo controller": "Pair a new controller",
  "posto {0}": "slot {0}",
  "non collegato": "not connected",
  "Impostazioni": "Settings",
  "Ricerca interrotta: riprova senza controller collegati.": "Scan interrupted: try again with no controllers connected.",
  "Già 5 reti salvate: eliminane una.": "5 networks already saved: delete one.",
  "mai": "never",
  "{0} fa": "{0} ago",
  "Rete": "Network",
  "WiFi del ricevitore": "Receiver WiFi",
  "connesso · IP {0} · segnale {1} dBm": "connected · IP {0} · signal {1} dBm",
  "spento: con i controller collegati la radio è tutta al Bluetooth": "off: with controllers connected the radio is all for Bluetooth",
  "Ultimo Wake-on-LAN": "Last Wake-on-LAN",
  "{0}. (vuota)": "{0}. (empty)",
  "{0} · password {1}": "{0} · password {1}",
  "salvata": "saved",
  "nessuna": "none",
  "Modifica": "Edit",
  "Aggiungi": "Add",
  "Spegni i controller: con un controller il WiFi è spento.": "Turn off the controllers: with a controller connected the WiFi is off.",
  "Password, indirizzo dal router e internet.": "Password, address from the router and internet.",
  "in corso...": "in progress...",
  "Prova": "Test",
  "Rete {0} eliminata.": "Network {0} deleted.",
  "Elimina": "Delete",
  "Reti visibili dal ricevitore (solo 2,4 GHz). Scegline una per salvarla.": "Networks visible to the receiver (2.4 GHz only). Choose one to save it.",
  "Ricerca...": "Scanning...",
  "Cerca reti": "Scan for networks",
  "Nessuna rete rilevata: il router trasmette a 2,4 GHz?": "No networks found: does the router broadcast on 2.4 GHz?",
  "{0}{1} {2} dBm · canale {3} · {4}": "{0}{1} {2} dBm · channel {3} · {4}",
  "aperta": "open",
  "protetta": "secured",
  "Usa questa rete": "Use this network",
  "nessuno": "none",
  "Serve il WiFi connesso, quindi nessun controller collegato.": "Needs the WiFi connected, so no controllers connected.",
  "Pacchetto Wake-on-LAN inviato.": "Wake-on-LAN packet sent.",
  "Prova il Wake-on-LAN": "Test Wake-on-LAN",
  "Spegni i controller: il firmware si carica e si installa solo senza controller collegati.": "Turn off the controllers: the firmware is uploaded and installed only with no controllers connected.",
  "Caricamento: {0} di {1} blocchi": "Uploading: {0} of {1} blocks",
  "Il ricevitore verifica il firmware (SHA-256)...": "The receiver is verifying the firmware (SHA-256)...",
  "Installazione: il ricevitore si riavvia (non staccarlo).": "Installing: the receiver restarts (do not unplug it).",
  "{0}: versione {1}, {2} KB": "{0}: version {1}, {2} KB",
  "installata: {0}": "installed: {0}",
  "Scegli il firmware (.uf2 o .bin)...": "Choose the firmware (.uf2 or .bin)...",
  "Annulla l'aggiornamento": "Cancel the update",
  "Carica, verifica e installa: servono i controller spenti.": "Upload, verify and install: the controllers must be off.",
  "Aggiorna il ricevitore": "Update the receiver",
  "Aggiornamento": "Updates",
  "Ultima versione {0}: firmware {1}": "Latest version {0}: firmware {1}",
  "da aggiornare": "update available",
  "aggiornato": "up to date",
  " ({0}), plugin {1} ({2}).": " ({0}), plugin {1} ({2}).",
  "ricevitore non collegato": "receiver not connected",
  "Controlla le release su GitHub.": "Check the releases on GitHub.",
  "Cerca aggiornamenti": "Check for updates",
  "Scarica da GitHub e installa: servono i controller spenti.": "Download from GitHub and install: the controllers must be off.",
  "Download del firmware avviato.": "Firmware download started.",
  "Installa il firmware {0}": "Install firmware {0}",
  "Scarica il plugin nuovo e riavvia Decky Loader (pochi secondi).": "Download the new plugin and restart Decky Loader (a few seconds).",
  "Plugin aggiornato: Decky Loader si riavvia.": "Plugin updated: Decky Loader is restarting.",
  "Aggiorna il plugin a {0}": "Update the plugin to {0}",
  "Cerca aggiornamenti all'avvio": "Check for updates at startup",
  "Al massimo una volta al giorno, con una notifica.": "At most once a day, with a notification.",
  "Download del firmware e copia nel Pico (circa 30 s)...": "Downloading the firmware and copying it to the Pico (about 30 s)...",
  "Ricevitore pronto: PS-RX {0} ({1}). Ora abbina un controller.": "Receiver ready: PS-RX {0} ({1}). Now pair a controller.",
  "Nuovo ricevitore": "New receiver",
  "Trovato un Raspberry Pi Pico in modalità BOOTSEL.": "Found a Raspberry Pi Pico in BOOTSEL mode.",
  "Collega un Pico 2 W nuovo (compare da solo) o uno già usato tenendo premuto BOOTSEL mentre lo colleghi.": "Connect a new Pico 2 W (it shows up by itself) or a used one while holding BOOTSEL as you plug it in.",
  "Installa l'ultimo firmware PS-RX.": "Install the latest PS-RX firmware.",
  "Installa PS-RX sul Pico": "Install PS-RX on the Pico",
  "altoparlante": "speaker",
  "microfono": "microphone",
  "Sistema": "System",
  "acceso da {0} · {1} sull'USB · audio: {2}": "up for {0} · {1} on USB · audio: {2}",
  "non in uso": "not in use",
  " · modifiche in attesa di salvataggio (a controller spenti)": " · changes waiting to be saved (with controllers off)",
  "Notifiche": "Notifications",
  "Controller collegato (posto, modello, modalità, batteria) e batteria in esaurimento.": "Controller connected (slot, model, mode, battery) and low battery.",
  "Il ricevitore si riavvia come chiavetta RP2350 (solo senza controller).": "The receiver restarts as an RP2350 drive (only with no controllers).",
  "Ricevitore in modalità BOOTSEL.": "Receiver in BOOTSEL mode.",
  "Modalità aggiornamento (BOOTSEL)": "Update mode (BOOTSEL)",
  "Di solito non serve: le modifiche si salvano da sole a controller spenti.": "Usually not needed: changes are saved automatically when the controllers are off.",
  "Impostazioni salvate.": "Settings saved.",
  "Salva ora": "Save now",
  "Impostazioni di fabbrica": "Factory settings",
  "Reti WiFi, Wake-on-LAN, controller abbinati e loro impostazioni restano.": "WiFi networks, Wake-on-LAN, paired controllers and their settings are kept.",
  "Ripristina": "Reset",
  "Impostazioni di fabbrica ripristinate.": "Factory settings restored.",
  "Registro spento: attiva \"Registro diagnostico\".": "Log off: turn on \"Diagnostic log\".",
  "Mostra il registro": "Show the log",
  "Ricevitore": "Receiver",
  "ricerca...": "scanning...",
};

let italiano = true;

/** Lingua di Steam (o del browser del menu): "it" se italiano, altrimenti "en". */
export function linguaSteam(): string {
  const w = window as unknown as { LocalizationManager?: { m_rgLocalesToUse?: string[] } };
  const codice = w.LocalizationManager?.m_rgLocalesToUse?.[0] ?? navigator.language ?? "";
  return codice.toLowerCase().startsWith("it") ? "it" : "en";
}

export function impostaLingua(codice: string): void {
  italiano = codice === "it";
}

/** Testo nella lingua attuale; {0}, {1}... sostituiti dai valori. */
export function t(testo: string, ...valori: unknown[]): string {
  const modello = italiano ? testo : (EN[testo] ?? testo);
  return valori.length ? modello.replace(/\{(\d+)\}/g, (m, i) => (Number(i) < valori.length ? String(valori[Number(i)]) : m)) : modello;
}

impostaLingua(linguaSteam());
